"""New tables of calculator

Revision ID: ac6502911cf5
Revises: 1c839fd47f76
Create Date: 2024-06-15 22:19:24.211827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6502911cf5'
down_revision = '1c839fd47f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory_calculator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('Electricty', sa.Integer(), nullable=True),
    sa.Column('vehicles', sa.Integer(), nullable=True),
    sa.Column('Distance', sa.Integer(), nullable=True),
    sa.Column('Diesel', sa.Integer(), nullable=True),
    sa.Column('Natural_gas', sa.Integer(), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_calculator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Electricty', sa.String(), nullable=True),
    sa.Column('Cooking_gas', sa.String(), nullable=True),
    sa.Column('Diesel', sa.String(), nullable=True),
    sa.Column('Coal', sa.String(), nullable=True),
    sa.Column('Biomass', sa.String(), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_calculator')
    op.drop_table('factory_calculator')
    # ### end Alembic commands ###
