"""create tables

Revision ID: b93e72db1382
Revises: 
Create Date: 2024-06-20 12:28:37.517687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b93e72db1382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('green_carbon', sa.String(), nullable=True),
    sa.Column('carbon_emmision', sa.String(), nullable=True),
    sa.Column('blue_carbon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('class_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_calculator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('Electricty', sa.Integer(), nullable=True),
    sa.Column('vehicles', sa.Integer(), nullable=True),
    sa.Column('Distance', sa.Integer(), nullable=True),
    sa.Column('Diesel', sa.Integer(), nullable=True),
    sa.Column('Natural_gas', sa.Integer(), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_calculator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Electricty', sa.String(), nullable=True),
    sa.Column('Cooking_gas', sa.String(), nullable=True),
    sa.Column('Diesel', sa.String(), nullable=True),
    sa.Column('Coal', sa.String(), nullable=True),
    sa.Column('Biomass', sa.String(), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_class',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], )
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ammount', sa.Integer(), nullable=True),
    sa.Column('to_us', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('carbon_credits', sa.Integer(), nullable=True),
    sa.Column('pricing', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('buy', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('transfer', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partners', sa.String(), nullable=True),
    sa.Column('soultions', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('articles', sa.String(), nullable=True),
    sa.Column('events', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resouces_channel',
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resouces_channel')
    op.drop_table('resource')
    op.drop_table('channel')
    op.drop_table('wallet')
    op.drop_table('user')
    op.drop_table('payment')
    op.drop_table('company_class')
    op.drop_table('chat')
    op.drop_table('home_calculator')
    op.drop_table('factory_calculator')
    op.drop_table('company')
    op.drop_table('class')
    # ### end Alembic commands ###
